### ISSUE TITLE
[ANDROID] Get "Invalid date" on real device

### ISSUE THREAD

**Issue by paolospag** [artem-russkikh/react-native-ntp-client#3]
Hi,
I'm trying to use this library to get network time in a chat system to avoid to get device date since the user can manually set the date/time on his device.

I'm testing with this example code retrieved from documentation:
```jsx
ntpClient.getNetworkTime("pool.ntp.org", 123, (error, date) => {
  if (error) {
    console.error(error);
    return;
  }
  console.log(date);
});
```

While on iOS simulator this works as expected (I haven't tried it on real iOS device yet), on real Android device I'm getting this error on console:
```log
'socket-0', 'bound to address:', '0.0.0.0', 'port:', 0
'socket-0', 'closing'
Invalid Date
'socket-0', 'closed'
```

What can this error be due to? Notice that I set a manual date/time to test this snippet. 

My packages.json:
```json
...
"react": "16.8.6",
"react-native": "0.60.6",
"react-native-clock-sync": "1.1.0-a",
"react-native-ntp-client": "1.0.0",
"react-native-udp": "2.6.1",
...
```

**Comment by filippoitaliano** [comment]
I can't see anything wrong. This is my production tested module with same dependencies versions:

```
import moment from 'moment';
import ntp from 'react-native-ntp-client';

const NTP_SERVER = 'ntp1.inrim.it';
const NTP_PORT = 123;

const getDateTimeFromServer = (server = NTP_SERVER) => new Promise((resolve, reject) => {
  ntp.ntpReplyTimeout = 5000;

  ntp.getNetworkTime(server, NTP_PORT, (err, date) => {
    if (err) reject(err);
    resolve(moment(date).format());
  });
});

export default { getDateTimeFromServer };
```

**Comment by paolospag** [comment]
This promise doesn't work for me, even if I use `moment` and set different NTP server I get the same error on Android:
```log
Invalid date
```

**Comment by paolospag** [comment]
It seems Android is unable to read the string set in [this variable](https://github.com/artem-russkikh/react-native-ntp-client/blob/master/lib/ntp-client.js#L108), causing the `Invalid Date` error.

If I try to change the string with a boolean `false` (which returns `Thu Jan 01 1970 01:00:00`), I get a valid but wrong date: `2089-11-27T14:40:07.609+01:00`

**Comment by filippoitaliano** [comment]
Are you using Hermes engine? I'm not using it for now specifically for different date handling than V8.

**Comment by paolospag** [comment]
Yes, I'm using Hermes engine... I suspected this was the problem, any workaround?

**Comment by filippoitaliano** [comment]
Not investigated yet... @artem-russkikh Any idea?

**Comment by artem-russkikh** [comment]
@paolospag thank you for the issue, I have no experience with Hermes for now

I will check it in next few days

**Comment by artem-russkikh** [comment]
@paolospag react-native-ntp-client@1.0.1 with fix is released on npm

**Comment by paolospag** [comment]
@artem-russkikh great news! Thank you so much for the job!

**Comment by ShivangiAgrawal** [comment]
Got the same issue yesterday on android, on emulator as well as real device with **Hermes** enabled. Worked perfectly fine when **Hermes** disabled. Also worked perfectly fine on iOS . I don't think this issue is resolved yet for react native. 

For this again, I had to disable Hermes engine that increased my app size significantly on android. Really need a solution.

**Comment by info-bit** [comment]
@ShivangiAgrawal We are using the latest version of react-native-ntp-client in production with Hermes enabled on the latest React Native stable release. I'm sorry you have issues. Please verify you always manage Dates in a standard format outside react-native-ntp-client. This issue is an example of what I'm saying https://github.com/facebook/react-native/issues/26187.
