### ISSUE TITLE
TypeError: dgram.createSocket is not a function. 

### ISSUE THREAD

**Issue by namitonefc** [artem-russkikh/react-native-ntp-client#6]
This is error is showing up with **React Native 0.62.2** and **react-native-udp 4.0.2**.

`TypeError: dgram.createSocket is not a function. (In 'dgram.createSocket("udp4")', 'dgram.createSocket' is undefined) `
 
This is located at  ntp-client.js:39:21

```
var client = dgram.createSocket("udp4"),
ntpData = new Buffer(48);
```

Will appreciate any help on this. This issue has become a blocker for us. Thanks.

**Comment by info-bit** [comment]
As you can see in the package.json react-native-ntp-client currently support react-native-udp up to version `^2.6.1`. If you use this version it should work fine. I understand the issue if you rely on a newer version of react-native-udp in your project. Unfortunately we can't work on this right now. If you are able to contribute with a PR it would be awesome!

**Comment by info-bit** [comment]
@namitonefc, is this issue still a thing after the latest release?

**Comment by info-bit** [comment]
I close the issue for now. Please comment if you still have some error showing up 🙏
