### ISSUE TITLE
ERROR_SOCKET_BAD_PORT

### ISSUE THREAD

**Issue by Averoes12** [artem-russkikh/react-native-ntp-client#7]
![screenshot-2020-09-18_09 22 59 103](https://user-images.githubusercontent.com/41353204/93548049-9fcf6f00-f990-11ea-8bb8-950abbacce5c.png)

anyone can help me please ?
i don't know what's the problem of my error 

this is my code 

    componentDidMount() {
        ntpClient.getNetworkTime("time.google.com",881, (error, date) => {
            if (error) {
                console.error(error);
                return;
            }

            console.log(date); // Mon Jul 08 2013 21:31:31 GMT+0200 (Paris, Madrid (heure d’été))
        });
    }
and in Log show this 

![error](https://user-images.githubusercontent.com/41353204/93548394-53386380-f991-11ea-9211-4b7dba151de1.png)

Thank you in advance

**Comment by NiloDrumond** [comment]
hey @Averoes12. Im also having this problem, have you managed to solve it?

**Comment by info-bit** [comment]
Did you try with the 123 standard UDP port? The error message is explicative. We don't have related issues on our side. Please, feel free to re-open if you find an issues with react-native-ntp-client codebase.

**Comment by winseyli** [comment]
Hi there. I am using
`ntpClient.getNetworkTime("pool.ntp.org", 123, (error, date) => {....`
and I got the same error.

My project was in RN 0.61.5 and I just branch my project and upgrade to RN 0.63.3

`getNetworkTime` works well on old master branch and my new branch with RN 0.63 got the `Timeout waiting for NTP response.` error.

**Comment by info-bit** [comment]
Hi, we are using RN 0.63.2 and we don't have any issue.

**Comment by Chocolladin** [comment]
ERROR_SOCKET_BAD_PORT with RN0.63.3 too

**Comment by Chocolladin** [comment]
updates : i noticed in peerdependency react-native-udp, in V4 there is this :

BREAKING CHANGES
All methods no longer check parameter types. socket.send() now throws 'ERR_SOCKET_BAD_PORT' when sending on unbound sockets. socket.send() no longer checks if �ddress is a valid IP or hostname.

so to make react-native-ntp-client work with this, i added the following (in bold) in lib/ntp-client.js :

exports.getNetworkTime = function (server, port, callback) {
    if (callback === null || typeof callback !== "function") {
        return;
    }

    server = server || exports.defaultNtpServer;
    port = port || exports.defaultNtpPort;

    var client = dgram.createSocket("udp4"),
        ntpData = new Buffer(48);

    **client.bind((e) => {
        if(e) console.log(e)
    });**
Regards
