### ISSUE TITLE
No client found with id 18

### ISSUE THREAD

**Issue by shadowphoenixpt** [artem-russkikh/react-native-ntp-client#8]
Every few requests I'm getting the above error (it's not always 18, though, it can be several other numbers). I have tried with several different NTP servers and I'm still getting this error. Any idea what could be going wrong?

**Comment by info-bit** [comment]
We willing to help you but we need more info. This is our production working code, latest module version, latest react-native version:

```js
const _getDateTimeFromServer = () => new Promise((resolve, reject) => {
  ntp.ntpReplyTimeout = 5000;

  ntp.getNetworkTime('ntp1.inrim.it', 123, (err, date) => {
    if (err) reject(err);
    resolve(moment(date).format());
  });
});
```

**Comment by shadowphoenixpt** [comment]
> We willing to help you but we need more info. This is our production working code, latest module version, latest react-native version:
> 
> ```js
> const _getDateTimeFromServer = () => new Promise((resolve, reject) => {
>   ntp.ntpReplyTimeout = 5000;
> 
>   ntp.getNetworkTime('ntp1.inrim.it', 123, (err, date) => {
>     if (err) reject(err);
>     resolve(moment(date).format());
>   });
> });
> ```

Thank you, but I found out that react-native-clock-sync doesn't have this problem and it suits my needs just as well.

**Comment by jonahweissman** [comment]
Sounds like https://github.com/tradle/react-native-udp/issues/118
