### ISSUE TITLE
ERROR_SOCKET_BAD_PORT with RN0.63.3

### ISSUE THREAD

**Issue by Chocolladin** [artem-russkikh/react-native-ntp-client#9]
getting : ERROR_SOCKET_BAD_PORT with RN0.63.3

**Comment by Chocolladin** [comment]
updates : i noticed in peerdependency react-native-udp, in V4 there is this : 

BREAKING CHANGES
All methods no longer check parameter types. **socket.send() now throws 'ERR_SOCKET_BAD_PORT' when sending on unbound sockets**. socket.send() no longer checks if �ddress is a valid IP or hostname.

so to make react-native-ntp-client work with this, i added the following (in bold) in lib/ntp-client.js : 

    exports.getNetworkTime = function (server, port, callback) {
        if (callback === null || typeof callback !== "function") {
            return;
        }

        server = server || exports.defaultNtpServer;
        port = port || exports.defaultNtpPort;

        var client = dgram.createSocket("udp4"),
            ntpData = new Buffer(48);

        **client.bind((e) => {
            if(e) console.log(e)
        });**

Regards

**Comment by info-bit** [comment]
As you can see in the package.json react-native-ntp-client currently support react-native-udp up to version ^2.6.1. If you use this version it should work fine. I understand the issue if you rely on a newer version of react-native-udp in your project. Unfortunately we can't work on this right now. If you are able to contribute with a PR it would be awesome!

**Comment by onebigdoor** [comment]
can confirm the above fix works.  here's a PR https://github.com/artem-russkikh/react-native-ntp-client/pull/10
